version: "2"
linters:
  enable:
    - errorlint
    - paralleltest
    - staticcheck
    - wrapcheck
  settings:
    paralleltest:
      ignore-missing: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - .NewAPIError(
        - .NewAPIErrorWrap(
        - .APIErrorFromRemoteError(
      ignore-sig-regexps:
        - \.New.*Error\(
      ignore-package-globs:
        - encoding/*
        - github.com/pkg/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(agola.io/agola)
        - blank
        - dot
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
