
// Code generated by go generate; DO NOT EDIT.
package db

import (
	stdsql "database/sql"

	"agola.io/agola/internal/sqlg/sql"

	"github.com/sorintlab/errors"
)

func (d *DB) Version() uint { return 2 }

func (d *DB) DDL() []string {
	switch d.DBType() {
	case sql.Postgres:
		return DDLPostgresV2
	case sql.Sqlite3:
		return DDLSqlite3V2
	}

	return nil
}

func (d *DB) Sequences() []string {
	return []string{
	}
}

func (d *DB) scanArray(rows *stdsql.Rows, colsList ...[]any) error {
	fields := []any{}
	for _, cols := range colsList {
		fields = append(fields, cols...)
	}
	if err := rows.Scan(fields...); err != nil {
		return errors.Wrap(err, "failed to scan row")
	}

	return nil
}
