version: v0

runs:
  - name: dart example
    tasks:
      - name: test
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: google/dart:latest
        steps:
          - clone:
          - run:
              name: Install dependencies
              command: pub get
          - run:
              name: Run tests
              commad: pub run test
