runs:
  - name: agola build/test
    tasks:
      - name: build go1.12
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.12-stretch
              environment:
                ENV01: envvalue01
        working_dir: /go/src/github.com/sorintlab/agola
        environment:
          GO111MODULE: "on"
          VAR01:
            from_variable: var01
        steps:
          - run: env
          - clone:
          - run: SKIP_DOCKER_TESTS=1 go test -v -count 1 ./...
      - name: build docker tests go1.12
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.12-stretch
              environment:
                ENV01: envvalue01
        working_dir: /go/src/github.com/sorintlab/agola
        environment:
          GO111MODULE: "on"
        steps:
          - run: env
          - clone:
          - run:
              name: build docker tests binary
              command: CGO_ENABLED=0 go test -c ./internal/services/runservice/executor/driver -o ./bin/docker-tests
              environment:
                ENV01: envvalue01
          - save_to_workspace:
              contents:
                - source_dir: ./bin
                  dest_dir: /bin/
                  paths:
                    - "*"
      - name: test docker driver
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: docker:stable-dind
              privileged: true
              entrypoint: dockerd
        steps:
          - run: env
          - restore_workspace:
              dest_dir: .
          - run: ./bin/docker-tests -test.parallel 1 -test.v
        depends:
          - build docker tests go1.12